library(ade4)
data("chazeb")
dis1 <- discrimin(dudi.pca(chazeb$tab, scan = FALSE), chazeb$cla,scan = FALSE)
pdf("Chazeb.pdf")
plot(dis1)
dev.off()
data("skulls")
pdf("Skulls.pdf")
plot(discrimin(dudi.pca(skulls,scan = F), gl(5,30),scan = F))
dev.off()